# Generated by Django 5.0 on 2025-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_project_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='synopsis_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='synopsis_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_fa',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
